CONST_LOG_ERROR  = 1  # error message will be displayed with red color
CONST_LOG_WARNING  = 2  # warning message will be displayed with blue color
CONST_LOG_OK  = 3  # OK message will be displayed with green color
CONST_LOG_HINT  = 4  # hint message will be displayed with yellow color
CONST_LOG_INFO  = 5  # info. message will be displayed with black color
CONST_LOG_VERBOSE  = 6  # verbose message will be displayed with gray color
CONST_CH1  = 0  # Channel 1 index
CONST_CH2  = 1  # Channel 2 index
CONST_CH3  = 2  # Channel 3 index
CONST_CH4  = 3  # Channel 4 index
CONST_CH5  = 4  # Channel 5 index
CONST_CH6  = 5  # Channel 6 index
CONST_CH7  = 6  # Channel 7 index
CONST_CH8  = 7  # Channel 8 index
CONST_CH9  = 8  # Channel 9 index
CONST_CH10  = 9  # Channel 10 index
CONST_CH11  = 10  # Channel 11 index
CONST_CH12  = 11  # Channel 12 index
CONST_CH13  = 12  # Channel 13 index
CONST_CH14  = 13  # Channel 14 index
CONST_CH15  = 14  # Channel 15 index
CONST_CH16  = 15  # Channel 16 index
CONST_CH17  = 16  # Channel 17 index
CONST_CH18  = 17  # Channel 18 index
CONST_CH19  = 18  # Channel 19 index
CONST_CH20  = 19  # Channel 20 index
CONST_CH21  = 20  # Channel 21 index
CONST_CH22  = 21  # Channel 22 index
CONST_CH23  = 22  # Channel 23 index
CONST_CH24  = 23  # Channel 24 index
CONST_CH25  = 24  # Channel 25 index
CONST_CH26  = 25  # Channel 26 index
CONST_CH27  = 26  # Channel 27 index
CONST_CH28  = 27  # Channel 28 index
CONST_CH29  = 28  # Channel 29 index
CONST_CH30  = 29  # Channel 30 index
CONST_CH31  = 30  # Channel 31 index
CONST_CH32  = 31  # Channel 32 index
CONST_APP_CAN_TYPE  = 0  # Application CAN channel type
CONST_APP_LIN_TYPE  = 1  # Application LIN channel type
CONST_APP_FLEXRAY_TYPE  = 2  # Application FlexRay channel type
CONST_APP_ETHERNET_TYPE  = 3  # Application Ethernet channel type
CONST_BUS_UNKNOWN_TYPE  = 0  # device type - unknown
CONST_TS_TCP_DEVICE  = 1  # device type - TS Virtual Channel
CONST_XL_USB_DEVICE  = 2  # device type - XL USB Device
CONST_TS_USB_DEVICE  = 3  # device type - TS USB Device
CONST_PEAK_USB_DEVICE  = 4  # device type - PEAK USB Device
CONST_KVASER_USB_DEVICE  = 5  # device type - Kvaser USB Device
CONST_ZLG_USB_DEVICE  = 6  # device type - ZLG USB Device
CONST_ICS_USB_DEVICE  = 7  # device type - ICS USB Device
CONST_TS_TC1005_DEVICE  = 8  # device type - TS TC1005 Device
CONST_CANABLE_DEVICE  = 9  # device type - CANable Device
CONST_STIM_STOPPED  = 0  # STIM Signal - Stopped State
CONST_STIM_RUNNING  = 1  # STIM Signal - Running State
CONST_STIM_PAUSED  = 2  # STIM Signal - Paused State
CONST_AM_NOT_RUN  = 0  # Graphic Program (Automation Module) Running State - not running state
CONST_AM_PREPARE_RUN  = 1  # Graphic Program (Automation Module) Running State - Prepare running state
CONST_AM_RUNNING  = 2  # Graphic Program (Automation Module) Running State - Running state
CONST_AM_PAUSED  = 3  # Graphic Program (Automation Module) Running State - Paused state
CONST_AM_STEPPING  = 4  # Graphic Program (Automation Module) Running State - Stepping state
CONST_AM_FINISHED  = 5  # Graphic Program (Automation Module) Running State - Finished state
CONST_SIGNAL_TYPE_CAN  = 0  # Signal Checker - TSignalType.stCANSignal
CONST_SIGNAL_TYPE_LIN  = 1  # Signal Checker - TSignalType.stLINSignal
CONST_SIGNAL_TYPE_SYSTEM_VAR  = 2  # Signal Checker - TSignalType.stSystemVar
CONST_SIGNAL_TYPE_FLEXRAY  = 3  # Signal Checker - TSignalType.stFlexRay
CONST_SIGNAL_TYPE_ETHERNET  = 4  # Signal Checker - TSignalType.stEthernet
CONST_SIGNAL_CHECK_ALWAYS  = 0  # Signal Checker - TSignalCheckKind.sckAlways
CONST_SIGNAL_CHECK_APPEAR  = 1  # Signal Checker - TSignalCheckKind.sckAppear
CONST_SIGNAL_CHECK_STATISTICS  = 2  # Signal Checker - TSignalCheckKind.sckStatistics
CONST_SIGNAL_CHECK_RISING_EDGE  = 3  # Signal Checker - TSignalCheckKind.sckRisingEdge
CONST_SIGNAL_CHECK_FALLING_EDGE  = 4  # Signal Checker - TSignalCheckKind.sckFallingEdge
CONST_SIGNAL_CHECK_MONOTONY_RISING  = 5  # Signal Checker - TSignalCheckKind.sckMonotonyRising
CONST_SIGNAL_CHECK_MONOTONY_FALLING  = 6  # Signal Checker - TSignalCheckKind.sckMonotonyFalling
CONST_SIGNAL_CHECK_FOLLOW  = 7  # Signal Checker - TSignalCheckKind.sckFollow
CONST_SIGNAL_CHECK_JUMP  = 8  # Signal Checker - TSignalCheckKind.sckJump
CONST_SIGNAL_CHECK_NO_CHANGE  = 9  # Signal Checker - TSignalCheckKind.sckNoChange
CONST_STATISTICS_MIN  = 0  # Signal Checker - TSignalStatisticsKind.sskMin
CONST_STATISTICS_MAX  = 1  # Signal Checker - TSignalStatisticsKind.sskMax
CONST_STATISTICS_AVERAGE  = 2  # Signal Checker - TSignalStatisticsKind.sskAverage
CONST_STATISTICS_STANDARD_DEVIATION  = 3  # Signal Checker - TSignalStatisticsKind.sskStdDeviation
CONST_SYMBOL_MAPPING_DIR_BIDIRECTION  = 0  # Symbol mapping direction - bidirection
CONST_SYMBOL_MAPPING_DIR_SGN_TO_SYSVAR  = 1  # Symbol mapping direction - from signal to sys var
CONST_SYMBOL_MAPPING_DIR_SYSVAR_TO_SGN  = 2  # Symbol mapping direction - from sys var to signal
CONST_SYSTEM_VAR_TYPE_INT32  = 0  # System Var Type - svtInt32
CONST_SYSTEM_VAR_TYPE_UINT32  = 1  # System Var Type - svtUInt32
CONST_SYSTEM_VAR_TYPE_INT64  = 2  # System Var Type - svtInt64
CONST_SYSTEM_VAR_TYPE_UINT64  = 3  # System Var Type - svtUInt64
CONST_SYSTEM_VAR_TYPE_UINT8ARRAY  = 4  # System Var Type - svtUInt8Array
CONST_SYSTEM_VAR_TYPE_INT32ARRAY  = 5  # System Var Type - svtInt32Array
CONST_SYSTEM_VAR_TYPE_INT64ARRAY  = 6  # System Var Type - svtInt64Array
CONST_SYSTEM_VAR_TYPE_DOUBLE  = 7  # System Var Type - svtDouble
CONST_SYSTEM_VAR_TYPE_DOUBLEARRAY  = 8  # System Var Type - svtDoubleArray
CONST_SYSTEM_VAR_TYPE_STRING  = 9  # System Var Type - svtString
CONST_CANFD_CONTROLLER_TYPE_CAN  = 0  # CAN FD Controller Type - fdtCAN
CONST_CANFD_CONTROLLER_TYPE_ISOCANFD  = 1  # CAN FD Controller Type - fdtISOCANFD
CONST_CANFD_CONTROLLER_TYPE_NonISOCANFD  = 2  # CAN FD Controller Type - fdtNonISOCANFD
CONST_CANFD_CONTROLLER_MODE_NORMAL  = 0  # CAN FD Controller Mode - fdmNormal
CONST_CANFD_CONTROLLER_MODE_ACKOFF  = 1  # CAN FD Controller Mode - fdmACKOff
CONST_CANFD_CONTROLLER_MODE_RESTRICTED  = 2  # CAN FD Controller Mode - fdmRestricted
CONST_ONLINE_REPLAY_TIMEING_IMMEDIATELY  = 0  # Online replay timing mode - ortImmediately
CONST_ONLINE_REPLAY_TIMEING_ASLOG  = 1  # Online replay timing mode - ortAsLog
CONST_ONLINE_REPLAY_TIMEING_DELAYED  = 2  # Online replay timing mode - ortDelayed
CONST_ONLINE_REPLAY_STATUS_NOTSTARTED  = 0  # Online replay status - orsNotStarted
CONST_ONLINE_REPLAY_STATUS_RUNNING  = 1  # Online replay status - orsRunning
CONST_ONLINE_REPLAY_STATUS_PAUSED  = 2  # Online replay status - orsPaused
CONST_ONLINE_REPLAY_STATUS_COMPLETED  = 3  # Online replay status - orsCompleted
CONST_ONLINE_REPLAY_STATUS_TERMINATED  = 4  # Online replay status - orsTerminated
CONST_BLF_OBJECT_CAN  = 0  # BLF Object Type - sotCAN
CONST_BLF_OBJECT_LIN  = 1  # BLF Object Type - sotLIN
CONST_BLF_OBJECT_CANFD  = 2  # BLF Object Type - sotCANFD
CONST_BLF_OBJECT_REALTIMECOMMENT  = 3  # BLF Object Type - sotRealtimeComment
CONST_BLF_OBJECT_SYSTEMVAR  = 4  # BLF Object Type - sotSystemVar
CONST_BLF_OBJECT_FLEXRAY  = 5  # BLF Object Type - sotFlexRay
CONST_BLF_OBJECT_ETHERNET  = 6  # BLF Object Type - sotEthernet
CONST_RBS_INIT_VALUE_OPTIONS_USEDB  = 0  # RBS Init Value Options - rivUseDB
CONST_RBS_INIT_VALUE_OPTIONS_USELAST  = 1  # RBS Init Value Options - rivUseLast
CONST_RBS_INIT_VALUE_OPTIONS_USE0  = 2  # RBS Init Value Options - rivUse0
CONST_AM_SIGNAL_TYPE_CANSIGNAL  = 0  # Graphic Program (Automation Module) Signal Type - lastCANSignal
CONST_AM_SIGNAL_TYPE_LINSIGNAL  = 1  # Graphic Program (Automation Module) Signal Type - lastLINSignal
CONST_AM_SIGNAL_TYPE_SYSVAR  = 2  # Graphic Program (Automation Module) Signal Type - lastSysVar
CONST_AM_SIGNAL_TYPE_LOCALVAR  = 3  # Graphic Program (Automation Module) Signal Type - lastLocalVar
CONST_AM_SIGNAL_TYPE_CONST  = 4  # Graphic Program (Automation Module) Signal Type - lastConst
CONST_AM_SIGNAL_TYPE_FLEXRAYSIGNAL  = 5  # Graphic Program (Automation Module) Signal Type - lastFlexRaySignal
CONST_AM_SIGNAL_TYPE_IMMEDIATEVALUE  = 6  # Graphic Program (Automation Module) Signal Type - lastImmediateValue
CONST_MP_FUNCTION_SOURCE_SYSTEMFUNC  = 0  # Mini Program Function Source - lmfsSystemFunc
CONST_MP_FUNCTION_SOURCE_MPLIB  = 1  # Mini Program Function Source - lmfsMPLib
CONST_MP_FUNCTION_SOURCE_INTERNAL  = 2  # Mini Program Function Source - lmfsInternal
CONST_MP_VAR_TYPE_INTEGER  = 0  # Mini Program Variable Type - lvtInteger
CONST_MP_VAR_TYPE_DOUBLE  = 1  # Mini Program Variable Type - lvtDouble
CONST_MP_VAR_TYPE_STRING  = 2  # Mini Program Variable Type - lvtString
CONST_MP_VAR_TYPE_CANMSG  = 3  # Mini Program Variable Type - lvtCANMsg
CONST_MP_VAR_TYPE_CANFDMSG  = 4  # Mini Program Variable Type - lvtCANFDMsg
CONST_MP_VAR_TYPE_LINMSG  = 5  # Mini Program Variable Type - lvtLINMsg
CONST_STIM_SIGNAL_STATUS_STOPPED  = 0  # STIM Signal Status - sssStopped
CONST_STIM_SIGNAL_STATUS_RUNNING  = 1  # STIM Signal Status - sssRunning
CONST_STIM_SIGNAL_STATUS_PAUSED  = 2  # STIM Signal Status - sssPaused
CONST_SIGNAL_TESTER_NO_ERROR  = 0  # No Error
CONST_SIGNAL_TESTER_CHECK_SIGNAL_NOT_EXISTS_IN_DB  = 1  # Check signal not exists in DB
CONST_SIGNAL_TESTER_MIN_BIGGER_THAN_MAX  = 2  # Minimum value larger than Maximum value
CONST_SIGNAL_TESTER_STAR_TTIME_BIGGER_THAN_END_TIME  = 3  # Start Time larger than End Time
CONST_SIGNAL_TESTER_TRIGGER_MIN_BIGGER_THAN_MAX  = 4  # Trigger Minimum value larger than maximum value
CONST_SIGNAL_TESTER_SIGNAL_COUNT_IS_0  = 5  # Check signal count is zero
CONST_SIGNAL_TESTER_FOLLOW_SIGNAL_NOT_EXISTS_IN_DB  = 6  # Follow signal not exists in DB
CONST_SIGNAL_TESTER_TRIGGER_SIGNAL_NOT_EXISTS_IN_DB  = 7  # Trigger signal not exists in DB
CONST_SIGNAL_TESTER_SIGNAL_FOLLOW_VIOLATION  = 8  # Signal follow violation
CONST_SIGNAL_TESTER_SIGNAL_MONOTONY_RISING_VIOLATION  = 9  # Signal Monotony Rising voilation
CONST_SIGNAL_TESTER_SIGNAL_MONOTONY_FALLING_VIOLATION  = 10  # Signal Monotony Falling violation
CONST_SIGNAL_TESTER_SIGNAL_NO_CHANGE_VIOLATION  = 11  # Signal no change violation
CONST_SIGNAL_TESTER_SIGNAL_VALUEOUTOFRANGE  = 12  # Signal value out of range
CONST_SIGNAL_TESTER_CAN_SIGNAL_NOT_EXISTS  = 13  # CAN signal not exists
CONST_SIGNAL_TESTER_LIN_SIGNAL_NOT_EXISTS  = 14  # LIN signal not signals
CONST_SIGNAL_TESTER_FLEXRAY_SIGNAL_NOT_EXISTS  = 15  # FlexRay signal not exists
CONST_SIGNAL_TESTER_SYSTEM_VAR_NOT_EXISTS  = 16  # System variable not exists
CONST_SIGNAL_TESTER_START_FAILED_DUE_TO_INVALID_CONF  = 17  # Signal tester start failed due to invalid configuration
CONST_SIGNAL_TESTER_SIGNAL_VALUE_NOT_EXISTS  = 18  # Check Signal value not exist
CONST_SIGNAL_TESTER_STATISTICS_CHECK_VIOLATION  = 19  # Statistics value not within required rang
CONST_SIGNAL_TESTER_TRIGGER_VALUE_NOT_EXISTS  = 20  # Trigger signal value not exist
CONST_SIGNAL_TESTER_FOLLOW_VALUE_NOT_EXISTS  = 21  # Follow signal value not exist
CONST_SIGNAL_TESTER_TRIGGER_VALUE_NEVER_IN_RANGE  = 22  # Trigger signal value never in rang
CONST_SIGNAL_TESTER_TIME_RANGE_NOT_TOUCHED  = 23  # Allowed time range not touche
CONST_SIGNAL_TESTER_RISING_NOT_DETECTED  = 24  # Check signal rising edge not detecte
CONST_SIGNAL_TESTER_FALLING_NOT_DETECTED  = 25  # Check signal falling edge not detecte
CONST_SIGNAL_TESTER_NOT_APPEARED  = 26  # Check Signal not appeared in rang
CONST_SIGNAL_TESTER_JUMP_NOT_DETECTED  = 27  # Check signal jump not detect
IDX_ERR_OK  = 0  # OK
IDX_ERR_IDX_OUT_OF_RANGE  = 1  # Index out of range
IDX_ERR_CONNECT_FAILED  = 2  # Connect failed
IDX_ERR_DEV_NOT_FOUND  = 3  # Device not found
IDX_ERR_CODE_NOT_VALID  = 4  # Error code not valid
IDX_ERR_ALREADY_CONNECTED  = 5  # HID device already connected
IDX_ERR_HID_WRITE_FAILED  = 6  # HID write data failed
IDX_ERR_HID_READ_FAILED  = 7  # HID read data failed
IDX_ERR_HID_TX_BUFF_OVERRUN  = 8  # HID TX buffer overrun
IDX_ERR_HID_TX_TOO_LARGE  = 9  # HID TX buffer too large
IDX_ERR_PACKET_ID_INVALID  = 10  # HID RX packet report ID invalid
IDX_ERR_PACKET_LEN_INVALID  = 11  # HID RX packet length invalid
IDX_ERR_INTERNAL_TEST_FAILED  = 12  # Internal test failed
IDX_ERR_RX_PACKET_LOST  = 13  # RX packet lost
IDX_ERR_HID_SETUP_DI  = 14  # SetupDiGetDeviceInterfaceDetai
IDX_ERR_HID_CREATE_FILE  = 15  # Create file failed
IDX_ERR_HID_READ_HANDLE  = 16  # CreateFile failed for read handle
IDX_ERR_HID_WRITE_HANDLE  = 17  # CreateFile failed for write handle
IDX_ERR_HID_SET_INPUT_BUFF  = 18  # HidD_SetNumInputBuffers
IDX_ERR_HID_GET_PREPAESED  = 19  # HidD_GetPreparsedData
IDX_ERR_HID_GET_CAPS  = 20  # HidP_GetCaps
IDX_ERR_HID_WRITE_FILE  = 21  # WriteFile
IDX_ERR_HID_GET_OVERLAPPED  = 22  # GetOverlappedResult
IDX_ERR_HID_SET_FEATURE  = 23  # HidD_SetFeature
IDX_ERR_HID_GET_FEATURE  = 24  # HidD_GetFeature
IDX_ERR_HID_DEVICE_IO_CTRL  = 25  # Send Feature Report DeviceIoContro
IDX_ERR_HID_SEND_FEATURE_RPT  = 26  # Send Feature Report GetOverLappedResult
IDX_ERR_HID_GET_MANU_STR  = 27  # HidD_GetManufacturerString
IDX_ERR_HID_GET_PROD_STR  = 28  # HidD_GetProductString
IDX_ERR_HID_GET_SERIAL_STR  = 29  # HidD_GetSerialNumberString
IDX_ERR_HID_GET_INDEXED_STR  = 30  # HidD_GetIndexedString
IDX_ERR_TX_TIMEDOUT  = 31  # Transmit timed out
IDX_ERR_HW_DFU_WRITE_FLASH_FAILED  = 32  # HW DFU flash write failed
IDX_ERR_HW_DFU_WRITE_WO_ERASE  = 33  # HW DFU write without erase
IDX_ERR_HW_DFU_CRC_CHECK_ERROR  = 34  # HW DFU crc check error
IDX_ERR_HW_DFU_COMMAND_TIMED_OUT  = 35  # HW DFU reset before crc check success
IDX_ERR_HW_PACKET_ID_INVALID  = 36  # HW packet identifier invalid
IDX_ERR_HW_PACKET_LEN_INVALID  = 37  # HW packet length invalid
IDX_ERR_HW_INTERNAL_TEST_FAILED  = 38  # HW internal test failed
IDX_ERR_HW_RX_FROM_PC_PACKET_LOST  = 39  # HW rx from pc packet lost
IDX_ERR_HW_TX_TO_PC_BUFF_OVERRUN  = 40  # HW tx to pc buffer overrun
IDX_ERR_HW_API_PARAMETER_INVALID  = 41  # HW API parameter invalid
IDX_ERR_DFU_FILE_LOAD_FAILED  = 42  # DFU file load failed
IDX_ERR_DFU_HEADER_WRITE_FAILED  = 43  # DFU header write failed
IDX_ERR_READ_STATUS_TIMEDOUT  = 44  # Read status timed out
IDX_ERR_CALLBACK_ALREADY_EXISTS  = 45  # Callback already exists
IDX_ERR_CALLBACK_NOT_EXISTS  = 46  # Callback not exists
IDX_ERR_FILE_INVALID  = 47  # File corrupted or not recognized
IDX_ERR_DB_ID_NOT_FOUND  = 48  # Database unique id not found
IDX_ERR_SW_API_PARAMETER_INVALID  = 49  # Software API parameter invalid
IDX_ERR_SW_API_GENERIC_TIMEOUT  = 50  # Software API generic timed out
IDX_ERR_SW_API_SET_CONF_FAILED  = 51  # Software API set hw config. failed
IDX_ERR_SW_API_INDEX_OUT_OF_BOUNDS  = 52  # Index out of bounds
IDX_ERR_SW_API_WAIT_TIMEOUT  = 53  # RX wait timed out
IDX_ERR_SW_API_GET_IO_FAILED  = 54  # Get I/O failed
IDX_ERR_SW_API_SET_IO_FAILED  = 55  # Set I/O failed
IDX_ERR_SW_API_REPLAY_ON_GOING  = 56  # An active replay is already running
IDX_ERR_SW_API_INSTANCE_NOT_EXISTS  = 57  # Instance not exists
IDX_ERR_HW_CAN_TRANSMIT_FAILED  = 58  # CAN message transmit failed
IDX_ERR_HW_NO_RESPONSE  = 59  # No response from hardware
IDX_ERR_SW_CAN_MSG_NOT_FOUND  = 60  # CAN message not found
IDX_ERR_SW_CAN_RECV_BUFFER_EMPTY  = 61  # User CAN receive buffer empty
IDX_ERR_SW_CAN_RECV_PARTIAL_READ  = 62  # CAN total receive count <> desired count
IDX_ERR_SW_API_LINCONFIG_FAILED  = 63  # LIN config failed
IDX_ERR_SW_API_FRAMENUM_OUTOFRANGE  = 64  # LIN frame number out of range
IDX_ERR_SW_API_LDFCONFIG_FAILED  = 65  # LDF config failed
IDX_ERR_SW_API_LDFCONFIG_CMDERR  = 66  # LDF config cmd error
IDX_ERR_SW_ENV_NOT_READY  = 67  # TSMaster envrionment not ready
IDX_ERR_SECURITY_FAILED  = 68  # reserved failed
IDX_ERR_XL_ERROR  = 69  # XL driver error
IDX_ERR_SEC_INDEX_OUTOFRANGE  = 70  # index out of range
IDX_ERR_STRINGLENGTH_OUTFOF_RANGE  = 71  # string length out of range
IDX_ERR_KEY_IS_NOT_INITIALIZATION  = 72  # key is not initialized
IDX_ERR_KEY_IS_WRONG  = 73  # key is wrong
IDX_ERR_NOT_PERMIT_WRITE  = 74  # write not permitted
IDX_ERR_16BYTES_MULTIPLE  = 75  # 16 bytes multiple
IDX_ERR_LIN_CHN_OUTOF_RANGE  = 76  # LIN channel out of range
IDX_ERR_DLL_NOT_READY  = 77  # DLL not ready
IDX_ERR_FEATURE_NOT_SUPPORTED  = 78  # Feature not supported
IDX_ERR_COMMON_SERV_ERROR  = 79  # common service error
IDX_ERR_READ_PARA_OVERFLOW  = 80  # read parameter overflow
IDX_ERR_INVALID_CHANNEL_MAPPING  = 81  # Invalid application channel mapping
IDX_ERR_TSLIB_GENERIC_OPERATION_FAILED  = 82  # libTSMaster generic operation failed
IDX_ERR_TSLIB_ITEM_ALREADY_EXISTS  = 83  # item already exists
IDX_ERR_TSLIB_ITEM_NOT_FOUND  = 84  # item not found
IDX_ERR_TSLIB_LOGICAL_CHANNEL_INVALID  = 85  # logical channel invalid
IDX_ERR_FILE_NOT_EXISTS  = 86  # file not exists
IDX_ERR_NO_INIT_ACCESS  = 87  # no init access, cannot set baudrate
IDX_ERR_CHN_NOT_ACTIVE  = 88  # the channel is inactive
IDX_ERR_CHN_NOT_CREATED  = 89  # the channel is not created
IDX_ERR_APPNAME_LENGTH_OUT_OF_RANGE  = 90  # length of the appname is out of range
IDX_ERR_PROJECT_IS_MODIFIED  = 91  # project is modified
IDX_ERR_SIGNAL_NOT_FOUND_IN_DB  = 92  # signal not found in database
IDX_ERR_MESSAGE_NOT_FOUND_IN_DB  = 93  # message not found in database
IDX_ERR_TSMASTER_IS_NOT_INSTALLED  = 94  # TSMaster is not installed
IDX_ERR_LIB_LOAD_FAILED  = 95  # Library load failed
IDX_ERR_LIB_FUNCTION_NOT_FOUND  = 96  # Library function not found
IDX_ERR_LIB_NOT_INITIALIZED  = 97  # cannot find libTSMaster.dll, use "set_libtsmaster_location" to set its location before calling initialize_lib_tsmaster
IDX_ERR_PCAN_GENRIC_ERROR  = 98  # PCAN generic operation error
IDX_ERR_KVASER_GENERIC_ERROR  = 99  # Kvaser generic operation error
IDX_ERR_ZLG_GENERIC_ERROR  = 100  # ZLG generic operation error
IDX_ERR_ICS_GENERIC_ERROR  = 101  # ICS generic operation error
IDX_ERR_TC1005_GENERIC_ERROR  = 102  # TC1005 generic operation error
IDX_ERR_SYSTEM_VAR_NOT_FOUND  = 103  # System variable not found
IDX_ERR_INCORRECT_SYSTEM_VAR_TYPE  = 104  # Incorrect system variable type
IDX_ERR_CYCLIC_MSG_NOT_EXIST  = 105  # Message not existing, update failed
IDX_ERR_BAUD_NOT_AVAIL  = 106  # Specified baudrate not available
IDX_ERR_DEV_NOT_SUPPORT_SYNC_SEND  = 107  # Device does not support sync. transmit
IDX_ERR_MP_WAIT_TIME_NOT_SATISFIED  = 108  # Wait time not satisfied
IDX_ERR_CANNOT_OPERATE_WHILE_CONNECTED  = 109  # Cannot operate while app is connected
IDX_ERR_CREATE_FILE_FAILED  = 110  # Create file failed
IDX_ERR_PYTHON_EXECUTE_FAILED  = 111  # Execute python failed
IDX_ERR_SIGNAL_MULTIPLEXED_NOT_ACTIVE  = 112  # Current multiplexed signal is not active
IDX_ERR_GET_HANDLE_BY_CHANNEL_FAILED  = 113  # Get handle by logic channel failed
IDX_ERR_CANNOT_OPERATE_WHILE_APP_CONN  = 114  # Cannot operate while application is connected, please stop application first
IDX_ERR_FILE_LOAD_FAILED  = 115  # File load failed
IDX_ERR_READ_LINDATA_FAILED  = 116  # Read LIN Data Failed
IDX_ERR_FIFO_NOT_ENABLED  = 117  # FIFO not enabled
IDX_ERR_INVALID_HANDLE  = 118  # Invalid handle
IDX_ERR_READ_FILE_ERROR  = 119  # Read file error
IDX_ERR_READ_TO_EOF  = 120  # Read to EOF
IDX_ERR_CONF_NOT_SAVED  = 121  # Configuration not saved
IDX_ERR_IP_PORT_OPEN_FAILED  = 122  # IP port open failed
IDX_ERR_IP_TCP_CONNECT_FAILED  = 123  # TCP connect failed
IDX_ERR_DIR_NOT_EXISTS  = 124  # Directory not exists
IDX_ERR_CURRENT_LIB_NOT_SUPPORTED  = 125  # Current library not supported
IDX_ERR_TEST_NOT_RUNNING  = 126  # Test is not running
IDX_ERR_SERV_RESPONSE_NOT_RECV  = 127  # Server response not received
IDX_ERR_CREATE_DIR_FAILED  = 128  # Create directory failed
IDX_ERR_INCORRECT_ARGUMENT_TYPE  = 129  # Invalid argument type
IDX_ERR_READ_DATA_PACKAGE_OVERFLOW  = 130  # Read Data Package from Device Failed
IDX_ERR_REPLAY_IS_ALREADY_RUNNING  = 131  # Precise replay is running
IDX_ERR_REPALY_MAP_ALREADY_EXIST  = 132  # Replay map is already
IDX_ERR_USER_CANCEL_INPUT  = 133  # User cancel input
IDX_ERR_API_CHECK_FAILED  = 134  # API check result is negative
IDX_ERR_CANABLE_GENERIC_ERROR  = 135  # CANable generic error
IDX_ERR_WAIT_CRITERIA_NOT_SATISFIED  = 136  # Wait criteria not satisfied
IDX_ERR_REQUIRE_APP_CONNECTED  = 137  # Operation requires application connected
IDX_ERR_PROJECT_PATH_ALREADY_USED  = 138  # Project path is used by another application
IDX_ERR_TP_TIMEOUT_AS  = 139  # Timeout for the sender to transmit data to the receiver
IDX_ERR_TP_TIMEOUT_AR  = 140  # Timeout for the receiver to transmit flow control to the sender
IDX_ERR_TP_TIMEOUT_BS  = 141  # Timeout for the sender to send first data frame after receiving FC frame
IDX_ERR_TP_TIMEOUT_CR  = 142  # Timeout for the receiver to receiving first CF frame after sending FC frame
IDX_ERR_TP_WRONG_SN  = 143  # Serial Number Error
IDX_ERR_TP_INVALID_FS  = 144  # Invalid flow status of the flow control frame
IDX_ERR_TP_UNEXP_PDU  = 145  # Unexpected Protocol Data Unit
IDX_ERR_TP_WFT_OVRN  = 146  # Wait counter of the FC frame out of the maxWFT
IDX_ERR_TP_BUFFER_OVFLW  = 147  # Buffer of the receiver is overflow
IDX_ERR_TP_NOT_IDLE  = 148  # TP Module is busy
IDX_ERR_TP_ERROR_FROM_CAN_DRIVER  = 149  # There is error from CAN Driver
IDX_ERR_TP_HANDLE_NOT_EXIST  = 150  # Handle of the TP Module is not exist
IDX_ERR_UDS_EVENT_BUFFER_IS_FULL  = 151  # UDS event buffer is full
IDX_ERR_UDS_HANDLE_POOL_IS_FULL  = 152  # Handle pool is full, can not add new UDS module
IDX_ERR_UDS_NULL_POINTER  = 153  # Pointer of UDS module is null
IDX_ERR_UDS_MESSAGE_INVALID  = 154  # UDS message is invalid
IDX_ERR_UDS_NO_DATA  = 155  # No uds data received
IDX_ERR_UDS_MODULE_NOT_EXISTING  = 156  # Handle of uds is not existing
IDX_ERR_UDS_MODULE_NOT_READY  = 157  # UDS module is not ready
IDX_ERR_UDS_SEND_DATA_FAILED  = 158  # Transmit UDS frame data failed
IDX_ERR_UDS_NOT_SUPPORTED  = 159  # This UDS Service is not supported
IDX_ERR_UDS_TIMEOUT_SENDING_REQUEST  = 160  # Timeout to send uds request
IDX_ERR_UDS_TIMEOUT_GET_RESPONSE  = 161  # Timeout to get uds response
IDX_ERR_UDS_NEGATIVE_RESPONSE  = 162  # Get uds negative response
IDX_ERR_UDS_NEGATIVE_WITH_EXPECTED_NRC  = 163  # Get uds negative response with expected NRC
IDX_ERR_UDS_NEGATIVE_UNEXPECTED_NRC  = 164  # Get uds negative response with unexpected NRC
IDX_ERR_UDS_CANTOOL_NOT_READY  = 165  # UDS CAN Tool is not ready
IDX_ERR_UDS_DATA_OUTOF_RANGE  = 166  # UDS Dta outof range
IDX_ERR_UDS_UNEXPECTED_FRAME  = 167  # Get Unexpected UDS frame
IDX_ERR_UDS_UNEXPECTED_POSTIVE_RESPONSE  = 168  # Receive unpexted positive response frame
IDX_ERR_UDS_POSITIVE_REPONSE_WITH_WRONG_DATA  = 169  # Receive positive response with wrong data
IDX_ERR_UDS_GET_POSITIVE_RESPONSE_FAILED  = 170  # Failed to get positive response
IDX_ERR_UDS_MaxNumOfBlockLen_OVER_FLOW  = 171  # MaxNumOfBlockLen out of range
IDX_ERR_UDS_NEGATIVE_RESPONSE_WITH_UNEXPECTED_NRC  = 172  # Receive negative response with unexpected NRC
IDX_ERR_UDS_SERVICE_IS_RUNNING  = 173  # UDS serive is busy
IDX_ERR_UDS_NEED_APPLY_DOWNLOAD_FIRST  = 174  # Apply download first before transfer data
IDX_ERR_UDS_RESPONSE_DATA_LENGTH_ERR  = 175  # Length of the uds reponse is wrong
IDX_ERR_TEST_CHECK_LOWER  = 176  # Verdict value smaller than specification
IDX_ERR_TEST_CHECK_UPPER  = 177  # Verdict value greater than specification
IDX_ERR_TEST_VERDICT_CHECK_FAILED  = 178  # Verdict check failed
IDX_ERR_AM_NOT_LOADED  = 179  # Graphic Program not loaded, please load it first
IDX_ERR_PANEL_NOT_FOUND  = 180  # Panel not found
IDX_ERR_CONTROL_NOT_FOUND_IN_PANEL  = 181  # Control not found in panel
IDX_ERR_PANEL_NOT_LOADED  = 182  # Panel not loaded, please load it first
IDX_ERR_STIM_SIGNAL_NOT_FOUND  = 183  # STIM signal not found
IDX_ERR_AM_SUB_MODULE_NOT_AVAIL  = 184  # Graphic Program sub module not available
IDX_ERR_AM_VARIANT_GROUP_NOT_FOUND  = 185  # Graphic Program variant group not found
IDX_ERR_PANEL_CONTROL_NOT_FOUND  = 186  # Control not found in panel
IDX_ERR_PANEL_CONTROL_NOT_SUPPORT_THIS  = 187  # Panel control does not support this property
IDX_ERR_RBS_NOT_RUNNING  = 188  # RBS engine is not running
IDX_ERR_MSG_NOT_SUPPORT_PDU_CONTAINER  = 189  # This message does not support PDU container
IDX_ERR_DATA_NOT_AVAILABLE  = 190  # Data not available
IDX_ERR_J1939_NOT_SUPPORTED  = 191  # J1939 not supported
IDX_ERR_J1939_ANOTHER_PDU_IS_SENDING  = 192  # Transmit J1939 PDU failed due to another PDU is already being transmitted
IDX_ERR_J1939_TX_FAILED_PROTOCOL_ERROR  = 193  # Transmit J1939 PDU failed due to protocol error
IDX_ERR_J1939_TX_FAILED_NODE_INACTIVE  = 194  # Transmit J1939 PDU failed due to node inactive
IDX_ERR_NO_LICENSE  = 195  # API is called without license support
IDX_ERR_SIGNAL_CHECK_RANGE_VIOLATION  = 196  # Signal range check violation
IDX_ERR_LOG_READ_CATEGORY_FAILED  = 197  # DataLogger read category failed
IDX_ERR_CHECK_BOOT_VERSION_FAILED  = 198  # Check Flash Bootloader Version Failed
IDX_ERR_LOG_FILE_NOT_CREATED  = 199  # Log file not created
IDX_ERR_MODULE_IS_BEING_EDITED_BY_USER  = 200  # the current module is being edited by user in dialog
IDX_ERR_LOG_DEVICE_IS_BUSY  = 201  # The Logger device is busy, can not operation at the same time
IDX_ERR_LIN_MASTER_TRANSMIT_N_AS_TIMEOUT  = 202  # Master node transmit diagnostic package timeout
IDX_ERR_LIN_MASTER_TRANSMIT_TRANSMIT_ERROR  = 203  # Master node transmit frame failed
IDX_ERR_LIN_MASTER_REV_N_CR_TIMEOUT  = 204  # Master node receive diagnostic package timeout
IDX_ERR_LIN_MASTER_REV_ERROR  = 205  # Master node receive frame failed
IDX_ERR_LIN_MASTER_REV_INTERLLEAVE_TIMEOUT  = 206  # Internal time runs out before reception is completed
IDX_ERR_LIN_MASTER_REV_NO_RESPONSE  = 207  # Master node received no response
IDX_ERR_LIN_MASTER_REV_SN_ERROR  = 208  # Serial Number Error when receiving multi frames
IDX_ERR_LIN_SLAVE_TRANSMIT_N_CR_TIMEOUT  = 209  # Slave node transmit diagnostic package timeout
IDX_ERR_LIN_SLAVE_REV_N_CR_TIMEOUT  = 210  # Slave node receive diagnostic pacakge timeout
IDX_ERR_LIN_SLAVE_TRANSMIT_ERROR  = 211  # Slave node transmit frames error
IDX_ERR_LIN_SLAVE_REV_ERROR  = 212  # Slave node receive frames error
IDX_ERR_CLOSE_FILE_FAILED  = 213  # Close file failed
IDX_ERR_CONF_LOG_FILE_FAILED  = 214  # Configure log file failed
IDX_ERR_CONVERT_LOG_FAILED  = 215  # Convert log file failed
IDX_ERR_HALTED_DUE_TO_USER_BREAK  = 216  # Operation halted due to user break
IDX_ERR_WRITE_FILE_FAILED  = 217  # Write file failed
IDX_ERR_UNKNOWN_OBJECT_DETECTED  = 218  # Unknown object detected
IDX_ERR_THIS_FUNC_SHOULD_BE_CALLED_IN_MP  = 219  # this function should be called in mini program thread
IDX_ERR_USER_CANCEL_WAIT  = 220  # user canceled wait
IDX_ERR_DECOMPRESS_DATA_FAILED  = 221  # Decompress data failed
IDX_ERR_AUTOMATION_OBJ_NOT_CREATED  = 222  # Automation object not created
IDX_ERR_ITEM_DUPLICATED  = 223  # Item duplicated
IDX_ERR_DIVIDE_BY_ZERO  = 224  # Divide by zero
IDX_ERR_REQUIRE_MINI_PROGRAM_RUNNING  = 225  # This operation requires mini program running
IDX_ERR_FORM_NOT_EXIST  = 226  # Form not exists
IDX_ERR_CANNOT_CONFIG_WHEN_DEVICE_RUNNING  = 227  # Can not config when the device is running
IDX_ERR_DATA_NOT_READY  = 228  # The data of the device is not ready
IDX_ERR_STOP_DEVICE_FAILED  = 229  # Stop device failed
IDX_ERR_PYTHON_CODE_CRASH  = 230  # Python code crashed
IDX_ERR_CONDITION_NOT_MET  = 231  # Condition not met
IDX_ERR_PYTHON_MODULE_NOT_DEPLOYED  = 232  # Cannot call API because Python module not deployed
IDX_ERR_UDS_CONNECT_DUT_FAILED  = 233  # Connect Ethernet DUT Failed
IDX_ERR_ETH_GENERIC_ACK  = 234  # Generic ACK of DOIP Frame
IDX_ERR_ETH_VEHILCE_INFO_RES  = 235  # Response of Vehicle Information
IDX_ERR_ETH_ACTIVATE_RES  = 236  # Response of Active Request
IDX_ERR_ETH_ALIVE_RES  = 237  # Response of Alive Request
IDX_ERR_ETH_NODE_STATE_RES  = 238  # Response of Node State
IDX_ERR_ETH_DIAG_POWER_MODE_RES  = 239  # Response of Diagnostic Power Mode
IDX_ERR_ETH_DIAG_POSITIVE_ACK  = 240  # Positive ACK of Diagnostic Request
IDX_ERR_ETH_DIAG_NEGATIVE_ACK  = 241  # Negative ACK of Diagnostic Request
IDX_ERR_ETH_VEHICLE_REQ_ID  = 242  # Vehicle ID Request
IDX_ERR_ETH_VEHICLE_REQ_EID_ID  = 243  # Vehicle ID with EID Request
IDX_ERR_ETH_VEHICLE_REQ_VIN_ID  = 244  # Vehicle ID with VIN Request
IDX_ERR_ETH_ACTIVE_REQ  = 245  # Routing Activation Request
IDX_ERR_ETH_ALIVE_REQ  = 246  # Alive Check Request
IDX_ERR_ETH_NODE_STATE_REQ  = 247  # Node State Request
IDX_ERR_ETH_DIAG_POWER_MODE_REQ  = 248  # Diagnostic Power Mode Request
IDX_ERR_ETH_DIAG_REQ_RES  = 249  # DOIP Reqeust And Response
IDX_ERR_SOCKET_PREPARE_ENVIROMENT_FIRST  = 250  # Please prepare enviroment in TSMaster first
IDX_ERR_ETH_RESERVED1  = 251  # Reserved1 for Ethernet
IDX_ERR_GP_MODULE_NOT_FOUND  = 252  # Graphic program module not found
IDX_ERR_GP_ACTION_NOT_FOUND  = 253  # Graphic program action not found
IDX_ERR_GP_CANNOT_INSERT_GOTO_BETWEEN_ACTIONS  = 254  # Graphic program Cannot insert goto between actions
IDX_ERR_GP_CANNOT_DELETE_ACTION_WITH_BOTH_DIR  = 255  # Graphic program Cannot delete action with both directions
IDX_ERR_GP_ENTRY_POINT_CANNOT_BE_DELETED  = 256  # Graphic program entry point cannot be deleted
IDX_ERR_GP_KIND_CANNOT_BE_CHANGED  = 257  # Graphic program action type cannot be changed
IDX_ERR_GP_INCORRECT_ACTION_TYPE  = 258  # Graphic program incorrect action type being edited
IDX_ERR_GP_INCORRECT_EXECUTION_KIND  = 259  # Graphic program incorrect execution kind being edited
IDX_ERR_GP_ACTION_GROUP_REQUIRED  = 260  # Graphic program action group required
IDX_ERR_GP_CANNOT_ADD_DOWNWARD_ACTION  = 261  # Graphic program cannot add downward action
IDX_ERR_GP_CANNOT_ADD_RIGHTWARD_ACTION  = 262  # Graphic program cannot add rightward action
IDX_ERR_RBS_NODE_SIMULATION_IS_NOT_ACTIVE  = 263  # RBS node simulation is not active
IDX_ERR_RBS_FRAME_INFO_NOT_FOUND  = 264  # RBS frame info not found
IDX_ERR_RBS_IS_NOT_ENABLED  = 265  # RBS engine is not enabled
IDX_ERR_GPG_EXCEL_FORMAT_INVALID  = 266  # Graphic program generator excel format invalid
IDX_ERR_GPG_EXCEL_UNKNOWN_OBJ  = 267  # Graphic program generator excel unknown object
IDX_ERR_GPG_EXCEL_OBJ_NOT_FOUND  = 268  # Graphic program generator excel object not found
IDX_ERR_GPG_EXCEL_OBJ_NOT_DEFINED  = 269  # Graphic program generator excel object not defined
IDX_ERR_MP_CODE_CRASH  = 270  # Mini program code crash
IDX_ERR_USER_ABORTED_OPERATION  = 271  # User aborted operation
IDX_ERR_INVALID_MEMORY_ADDRESS  = 272  # Invalid memory address
IDX_ERR_IP_FRAGMENTATION_NEED  = 273  # Fragmentation is needed when building IPv4 packet
IDX_ERR_IP_IPV4_ID_REQUIRED  = 274  # IPv4 Id is required
IDX_ERR_SYS_VAR_NOT_EXISTS  = 275  # System variable not exists
IDX_ERR_WRITE_DEVICE_INT_CONFIG_FAILED  = 276  # Write internal configuration of Device(such as TC1011 Etc) Failed
IDX_ERR_READ_DEVICE_INT_CONFIG_FAILED  = 277  # Read internal configuration of Device(such as TC1011 Etc) Failed
IDX_ERR_ARGUMENT_COUNT_DIFFER  = 278  # API caller argument count differ
IDX_ERR_API_CALLER_CALL_FAILED  = 279  # API caller call API failed
IDX_ERR_ETH_FRAME_IS_NOT_IP  = 280  # Current ethernet frame is not IP frame
IDX_ERR_ETH_FRAME_IS_NOT_TCP  = 281  # Current ethernet frame is not TCP frame
IDX_ERR_ETH_FRAME_IS_NOT_UDP  = 282  # Current ethernet frame is not UDP frame
IDX_ERR_ETH_FRAME_DOES_NOT_CONTAIN_CRC  = 283  # Current ethernet frame does not contain CRC
IDX_ERR_ETH_API_REQUIRES_SINGLE_FRAME  = 284  # This API requires single frame, not fragment frame
IDX_ERR_ITEM_NOT_ENABLED  = 285  # This item is not enabled in configuration
IDX_ERR_ITEM_CONFIGURATION_NOT_VALID  = 286  # This item configuration is not valid
IDX_ERR_RESERVED01  = 287  # Reserved definition
IDX_ERR_SHOULD_START_BATCH_FIRST  = 288  # Should start batch first before this operation
IDX_ERR_TEST_SYSTEM_MODULE_NOT_LOADED  = 289  # Test system module not loaded
IDX_ERR_VISA_COMMAD_FAILED  = 290  # VISA Command failed
IDX_ERR_VISA_DEVICE_NOT_READY  = 291  # VISA Device not ready
IDX_ERR_ADD_INSTRUMENT_FAILED  = 292  # Add new instrument failed
IDX_ERR_LANG_KEY_NOT_FOUND  = 293  # Language item not found ini ini file
IDX_ERR_MAC_ADDRESS_NOT_EXITS  = 294  # Mac Address not exists in router table
IDX_ERR_IP_PORT_NOT_EXISTS  = 295  # IP and Port not exists in router table
IDX_ERR_CRITICAL_SECTION_ENTER_FAILED  = 296  # Critical section try enter failed
IDX_ERR_REQUIRE_APP_DISCONNECTED  = 297  # This operation requires application disconnected
IDX_ERR_SOCKET_ALREADY_EXISTS  = 298  # This socket is ready exists
IDX_ERR_SOCKET_NOT_EXISTS  = 299  # This socket is not exists
IDX_ERR_INVALID_IPV4_ENDPOINT  = 300  # The IPV4 Endpoint is invalid
IDX_ERR_TCP_CLIENT_NOT_SUPPORT_THIS_FEATURE  = 301  # TCP Client not support this feature
IDX_ERR_TCP_SERVER_NOT_SUPPORT_THIS_FEATURE  = 302  # TCP Server not support this feature
IDX_ERR_TCP_CLIENT_CONNECT_FAILED  = 303  # TCP Client connect to server failed
IDX_ERR_TCP_START_LISTEN_FAILED  = 304  # TCP Server start listen failed
IDX_ERR_TCP_DUPLICATE_START_LISTEN  = 305  # TCP Server start listen repeatedly is not allowed
IDX_ERR_CREATE_SOCKET_FAILED  = 306  # Create socket failed
IDX_ERR_RPC_SERVER_NOT_ACTIVATED  = 307  # RPC Server not activated
IDX_ERR_RPC_CLIENT_NOT_ACTIVATED  = 308  # RPC Client not activated
IDX_ERR_RPC_CALL_FAILED  = 309  # RPC call failed
IDX_ERR_TSMASTER_NOT_IN_COSIMULATION  = 310  # TSMaster is not in co-simulation mode
IDX_ERR_OBJECT_NOT_CREATED  = 311  # Object not created
IDX_ERR_OPERATION_NOT_SUPP_IN_BATCH_MODE  = 312  # Operation not supported in batch mode
IDX_ERR_NOT_IMPLEMENTED  = 313  # Not implemented
IDX_ERR_OPERATION_PENDING  = 314  # Operation is pending
IDX_ERR_COMPILE_FAILED  = 315  # Compile failed
IDX_ERR_RPC_SERVER_RUN_FAILED  = 316  # Rpc Server run failed
IDX_ERR_RPC_COMMAND_INVALID  = 317  # Invalid Rpc Command
IDX_ERR_INIT_SIMULATION_FAILED  = 318  # Initialize simulation failed
IDX_ERR_SIM_RUN_TO_END  = 319  # Simulation has run to end
IDX_ERR_SIM_VAR_INVALID  = 320  # Simulation variable invalid
IDX_ERR_COM_SERVER_FAILED  = 321  # COM server encounter error
IDX_ERR_APP_NOT_CONNECTED  = 322  # Current application is not connected
IDX_ERR_LOGIN_FAILED  = 323  # Login failed
IDX_ERR_SIGNAL_NOT_INITIALIZED  = 324  # Signal does not appear
IDX_ERR_DIR_SHOULD_BE_EMPTY  = 325  # Directory should be empty
IDX_ERR_FMIL_LOAD_DLL_FAILED  = 326  # FMI dll load failed
IDX_ERR_FMIL_GET_PROC_ADDRESS_FAILED  = 327  # FMI get process address failed
IDX_ERR_FMIL_UNLOAD_DLL_FAILED  = 328  # FMI dll unload failed
IDX_ERR_FMIL_API_NOT_IMPL  = 329  # FMI API not implemented
IDX_ERR_FMIL_FMI_VERSION_UNKNOWN  = 330  # FMI version unknown
IDX_ERR_FMIL_FMI_VERSION_UNSUPPORTED  = 331  # FMI version unsupported
IDX_ERR_FMIL_FMI_IMPORT_UNEXPECTED  = 332  # FMI import unexpected
IDX_ERR_FMIL_FMI_FMU_ALREADY_LOADED  = 333  # FMI FMU already loaded
IDX_ERR_FMIL_FMI_RESERVED1  = 334  # FMI reserved 1
IDX_ERR_FMIL_FMI_RESERVED2  = 335  # FMI reserved 2
IDX_ERR_FMIL_FMI_RESERVED3  = 336  # FMI reserved 3
IDX_ERR_TSMASTER_RPC_IP_PLUGIN_NOT_LOADED  = 337  # TSMaster Rpc Ip plugin not loaded
IDX_ERR_REQUIRE_GP_NOT_RUNNING  = 338  # This operation requires graphic program not in running state
IDX_ERR_JAVA_JVM_RUN_FAILED  = 339  # Java virtual machine run failed
IDX_ERR_JAVA_CLASS_NOT_FOUND  = 340  # Java class not found
IDX_ERR_JAVA_JVM_NOT_RUNNING  = 341  # Java virtual machine is not running
IDX_ERR_JAVA_JVM_ATTACH_THREAD_FAILED  = 342  # Java virtual machine attach thread failed
IDX_ERR_JAVA_CREATION_METHOD_NOT_FOUND  = 343  # Java class creation method not found
IDX_ERR_JAVA_OBJ_METHOD_NOT_FOUND  = 344  # Java object method not found
IDX_ERR_JAVA_STATIC_METHOD_NOT_FOUND  = 345  # Java class static method not found
IDX_ERR_JAVA_API_NOT_VALID  = 346  # Java API not valid
IDX_ERR_JAVA_API_ARG_COUNT_DIFFER  = 347  # Java API argument count differ
IDX_ERR_JAVA_API_ARG_INVALID  = 348  # Java API argument invalid
IDX_ERR_JAVA_API_OBJ_CREATE_FAILED  = 349  # Java API object create failed
IDX_ERR_JAVA_API_RETN_NOT_SUPPORTED  = 350  # Java API return value type not supported
IDX_ERR_JAVA_API_ACCESS_VIOLATION  = 351  # Java API access violation
IDX_ERR_JAVA_RESERVED1  = 352  # Java reserved 1
IDX_ERR_JAVA_RESERVED2  = 353  # Java reserved 2
IDX_ERR_JAVA_RESERVED3  = 354  # Java reserved 3
IDX_ERR_JAVA_RESERVED4  = 355  # Java reserved 4
IDX_ERR_JAVA_RESERVED5  = 356  # Java reserved 5
IDX_ERR_JAVA_RESERVED6  = 357  # Java reserved 6
IDX_ERR_JAVA_RESERVED7  = 358  # Java reserved 7
IDX_ERR_JAVA_RESERVED8  = 359  # Java reserved 8
IDX_ERR_PREREQUISITE_NOT_SATISFIED  = 360  # prerequisite not satisfied
IDX_ERR_SWITCH_HW_DIAG_MODE_FIRST  = 361  # Switch the transport layer to run on the real-time system
IDX_ERR_MBD_NOT_LOADED  = 362  # MBD module not loaded
IDX_ERR_MODEL_IS_ALREADY_RUNNING  = 363  # Model is already running
IDX_ERR_INVALID_MODEL_CONFIG  = 364  # Invalid model configuration
IDX_ERR_INVALID_DATA_TYPE  = 365  # Invalid data type
IDX_ERR_MODEL_INIT_FAILED  = 366  # Model initialization failed
IDX_ERR_MODEL_STEP_FAILED  = 367  # Model step failed
IDX_ERR_MODEL_NOT_FOUND  = 368  # Model not found
IDX_ERR_MODEL_STOP_FAILED  = 369  # Model stop failed
IDX_ERR_MODEL_SET_INPUT_FAILED  = 370  # Model set input failed
IDX_ERR_MODEL_GET_OUTPUT_FAILED  = 371  # Model get output failed
IDX_ERR_FEATURE_NOT_SUPPORTED_IN_CUR_CONFIG  = 372  # Feature not supported in current configuration
IDX_ERR_RPC_LOCAL_RX_SHARED_MEM_OPEN_FAIL1  = 373  # Local Rpc Rx shared memory open failed 1
IDX_ERR_RPC_LOCAL_RX_SHARED_MEM_OPEN_FAIL2  = 374  # Local Rpc Rx shared memory open failed as existing memory size smaller than request
IDX_ERR_RPC_LOCAL_RX_SHARED_MEM_OPEN_FAIL3  = 375  # Local Rpc Rx shared memory open failed 3
IDX_ERR_RPC_LOCAL_RX_SHARED_MEM_OPEN_FAIL4  = 376  # Local Rpc Rx shared memory open failed 4
IDX_ERR_RPC_LOCAL_RX_SHARED_MEM_OPEN_FAIL5  = 377  # Local Rpc Rx shared memory open failed 5
IDX_ERR_RPC_LOCAL_TX_SHARED_MEM_OPEN_FAIL1  = 378  # Local Rpc Tx shared memory open failed 1
IDX_ERR_RPC_LOCAL_TX_SHARED_MEM_OPEN_FAIL2  = 379  # Local Rpc Tx shared memory open failed as existing memory size smaller than request
IDX_ERR_RPC_LOCAL_TX_SHARED_MEM_OPEN_FAIL3  = 380  # Local Rpc Tx shared memory open failed 3
IDX_ERR_RPC_LOCAL_TX_SHARED_MEM_OPEN_FAIL4  = 381  # Local Rpc Tx shared memory open failed 4
IDX_ERR_RPC_LOCAL_TX_SHARED_MEM_OPEN_FAIL5  = 382  # Local Rpc Tx shared memory open failed 5
